/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab.dennis.primefactor;

import org.junit.BeforeClass;
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class PrimeFactorTest {
    private static PrimeFactor primeFactor;

    @BeforeClass
    public static void setUp() {
        primeFactor = new PrimeFactor();
    }

    @Test
    public void generate_one_correct() {
        assertThat(primeFactor.generate(1)).isEmpty();
    }

    @Test
    public void generate_two_correct() {
        assertThat(primeFactor.generate(2)).containsExactly(2);
    }

    @Test
    public void generate_three_correct() {
        assertThat(primeFactor.generate(3)).containsExactly(3);
    }

    @Test
    public void generate_four_correct() {
        assertThat(primeFactor.generate(4)).containsExactly(2,2);
    }
}
