/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab.dennis.primefactor;

import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class PrimeFactorTest {
    @Test
    public void generate_one_correct() {
        PrimeFactor primeFactor = new PrimeFactor();
        assertThat(primeFactor.generate(1)).contains(1);
    }
}
