/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab.dennis.primefactor;

import java.util.List;

public class PrimeFactor {
    public List<Integer> generate(int n) {
        return List.of(1);
    }
}
