/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab.dennis.primefactor;

import java.util.Collections;
import java.util.List;

public class PrimeFactor {
    public List<Integer> generate(int n) {
        if (n > 1) {
            return List.of(2);
        }
        return Collections.emptyList();
    }
}
